#Use actionbars instead of chat messages
#Disabled in GUI's by default because it may not be visable for larger GUI scales
Actionbars:
  enable: true
  use-in-GUI: false

#Command alias to use instead of /eglow
Command-alias:
  enable: false
  alias: "glow"
  
#Delay speed for effects
Delays:
  slow: 2.0
  fast: 1.0
  
#Make eGlow handle the formatting of the tab/tag
#Nametag will always have the glow, to help change this check out this:
#https://feedback.minecraft.net/hc/en-us/community/posts/360075673311
Formatting:
  tablist:
    enable: false
    format: "%prefix% &r%name% %suffix%"
  tagname:
    enable: false
    prefix: "%prefix%"
    suffix: "%suffix"

#Store player data in a MySQL database
MySQL:
  enable: false
  host: "localhost"
  port: 3306
  DBName: ""
  username: "root"
  password: "123"

#Block/allow glowing in certain worlds
World:
  enable: false
  action: block
  worlds:
    - "world1"
    - "world2"
   
Settings:
  disable-glow-when-invisible: true
  smart-TAB-nametag-handler: false
  gui:
    render-skulls: true
    add-glass-panes: true
    add-prefix-to-title: true
    #Enabling this setting requires you to manually add the colors to the GUI section
    #of the messages.yml
    use-gui-color-for-messages: false
    max-personal-effect-size: 10
  join:
    check-glow-permission: false
    default-glow-on-join-value: true
    mention-glow-state: false
    #Configure effects to force on players/groups (using permission)
    force-glows:
      enable: false
      bypass-blocked-worlds: false
      glows:
        #permission: eglow.force.founder
        founder: "rainbowfast" 
        #permission: eglow.force.vip
        vip: "gold" 
  notifications:
    plugin-update: true
    invisibility-change: true
    target-set-unset-command: true

#Advanced settings - Only edit these when you know what you're doing!
#Disabling some of these settings may cause eGlow to not work properly
Advanced:
  #This setting will be able to hide the glow behind objects
  glow-visibility:
    enable: false
    delay: 0.5 #half a second is the hardcoded minimum! This to prevent possible performance issues
  MySQL:
    useSSL: true
  teams:
    entity-collision: true
    nametag-visibility: true
    #Mainly aimed towards proxy networks to prevent 'Team already exists' kick
    remove-teams-on-join: true
    #Allows eGlow to set the proper glow color
    #automatically disabled when using TAB
    send-eGlow-team-packets: true
  packets:
    #Allows eGlow to modify team packets that would break the glow color
    #automatically disabled when using TAB
    smart-packet-blocker: true